Added initial columns block styling
hlxsites/troweprice-rf pull request #20
Opened 2023-06-21 11:51 UTC by dnbute

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #7 

Test URLs:
- Before: https://main--troweprice-rf--hlxsites.hlx.page/
- After: https://columns--troweprice-rf--hlxsites.hlx.page/

2023-06-21 19:51 UTC, bstopp requested changes
I moved the source to a draft page. But before this can be merged need to rebase, and look compare the experience at the different breakpoints: <600 (i use 300px), 600, 900, 1200. The mobile view isn't using the right font sizes/weights.

2023-06-21 19:51 UTC, bstopp commented on blocks/columns/columns.css
> +.columns > div > div > p:first-child::after {
This bottom border experience is more of a global h4 experience. We should look at moving that to the `styles.css` and then the authors will use h4 in the content to drive that experience

2023-06-21 19:51 UTC, bstopp commented on blocks/columns/columns.css
> +  color: #3b4b59;
Colors should always use variables so we can make updates easily. This also seems like it's the default color for all content? If so we can push this up to `styles.css`, if it hasn't been added already.

2023-06-21 19:51 UTC, bstopp commented on blocks/columns/columns.css
> +  margin-block-end: 24px;
These i believe are a copy over from the live site? I have yet to see any use for the `margin-block...` set of styles. Other options provide more robust and flexible options.

2023-06-21 19:51 UTC, bstopp commented on blocks/columns/columns.css
> +    font-size: 30px;
this makes the assumption that the first p is a title, where as the authors should use h4 in the content, which will come over as a literal `<h4>` element. Allowing for better targetting of styling

2023-06-22 06:34 UTC, dnbute commented on blocks/columns/columns.css
> +  color: #3b4b59;
Yeah, I was waiting for your PR to be merged before I added stuff to the global styles.css

2023-06-22 06:38 UTC, dnbute commented on blocks/columns/columns.css
> +  margin-block-end: 24px;
I'm not sure if they're used on the live site but from what I know they're equivalent to the `margin-top -bot` etc but keep the same "positioning" regardless of writing direction, like `margin-inline-start` will be at the beginning of the writing, I don't think the website supports right to left writing so it might not be necessary, I can change them if you think it's better that way

2023-06-22 06:39 UTC, dnbute commented on blocks/columns/columns.css
> +    font-size: 30px;
Good point, I'll update this to target `<h4>` elements

2023-06-22 06:57 UTC, dnbute commented on blocks/columns/columns.css
> +    font-size: 30px;
Or rather remove it since it's in `styles.css`

2023-06-23 14:31 UTC, bstopp commented
I broke the third variation by changing the source content (again). Just need to add logic so that the `no-wrap` class ensures the columns don't wrap to next line.

2023-06-26 15:15 UTC, bstopp commented on blocks/columns/columns.css
>  .columns > div > .columns-img-col {
Is this used anywhere?

2023-06-26 15:18 UTC, bstopp commented on blocks/columns/columns.css
> +  font-size: var(--heading-font-size-xs);
is this the right font size for these h3? What makes it different than a global h3 definition?

2023-06-26 15:19 UTC, bstopp commented on blocks/columns/columns.css
> +.columns.icons h3 {
should be more specific here or less specific on line 28.

2023-06-26 15:21 UTC, bstopp commented on blocks/columns/columns.css
> +.columns-wrapper {
Don't apply styles to the wrapper; this is outside the scope of the block. (Same as line 66 in this file).

if we need padding to make the page content the same size, that should be a global `section` definition.

Section global styles will likely end up being:

* Padding at each breakpoint
* Reach max width, set max width and auto margins

2023-06-27 07:16 UTC, dnbute commented on blocks/columns/columns.css
>  .columns > div > .columns-img-col {
I removed all unused css

2023-06-27 07:17 UTC, dnbute commented on blocks/columns/columns.css
> +  font-size: var(--heading-font-size-xs);
Moved everything h3 related to global styles

2023-06-27 07:17 UTC, dnbute commented on blocks/columns/columns.css
> +.columns.icons h3 {
Went for less specific on both

2023-06-27 19:31 UTC, bstopp approved these changes

2023-06-28 06:52 UTC, merged