added tabs
hlxsites/troweprice-rf pull request #24
Opened 2023-06-23 10:34 UTC by sergiucoman

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #10

Test URLs:
- Before: https://main--troweprice-rf--hlxsites.hlx.page/
- After: https://feat-tabs--troweprice-rf--hlxsites.hlx.page/drafts/tabs

2023-06-26 13:47 UTC, bstopp requested changes
<img width="752" alt="Investing_Basics" src="https://github.com/hlxsites/troweprice-rf/assets/6520270/89fda8ac-5c0a-4866-a793-f317011d0ecb">

<img width="722" alt="Investing_Basics" src="https://github.com/hlxsites/troweprice-rf/assets/6520270/d7f59831-cb57-4a1e-a527-505efc127067">

2023-06-26 13:47 UTC, bstopp commented on styles/styles.css
> +    font-size: var(--body-font-size-xl);
you don't have to re-declare this, since it will apply from the smaller breakpoint.

2023-06-26 13:47 UTC, bstopp commented on styles/styles.css
> +  color: #3b4b59;
this is the `--charcoal` var.

2023-06-26 13:47 UTC, bstopp commented on styles/styles.css
> +  font-size: var(--body-font-size-l);
everything should be wrapped in a `p` tag. So we can probably make these font declarations (and color) global default paragraph settings. its like this in the Hero PR.

2023-06-27 08:36 UTC, dnbute commented on styles/styles.css
> +    font-size: 28px;
maybe use the variables instead of using the actual values, there's lots declared in the columns PR if you wanna copy those

2023-06-27 08:44 UTC, dnbute commented on styles/styles.css
> +main .section h4::after {
I think all headings with the underline thing look basically the same, let's sync on this since my h3 decoration is implemented a bit differently

2023-06-27 12:26 UTC, sergiucoman commented on styles/styles.css
> +main .section h4::after {
@dnbute , let's create a new PR with the global styles (p, h1-h5, etc). I do not think we should both "polute" the tabs or columns PR with the global styling and then have conflicts afterward.

2023-06-27 12:27 UTC, sergiucoman commented on styles/styles.css
> +  font-size: var(--body-font-size-l);
@bstopp , I would suggest @dnbute to create a new PR with the global styling as we have both implemented some changes in the styles.css and will run into conflicts.

2023-06-27 14:18 UTC, bstopp submitted a review, later dismissed
Gonna need a rebase with global styles. but this looks good.

2023-06-27 19:36 UTC, bstopp requested changes

2023-06-27 19:36 UTC, bstopp commented on blocks/tabs/tabs.css
> +.tabs-container {
This is outside the scope of the block, needs to be removed. Can be handled by global section defintiions

2023-06-27 19:36 UTC, bstopp commented on blocks/tabs/tabs.css
> +    line-height: 20px;
Please use the vars that determine line height relative to the font size. May not have one that's exactly 20px, but closest is good enough.

2023-06-27 19:49 UTC, sergiucoman commented on blocks/tabs/tabs.css
> +.tabs-container {
removed.

2023-06-27 19:49 UTC, sergiucoman commented on blocks/tabs/tabs.css
> +    line-height: 20px;
done

2023-06-28 13:52 UTC, bstopp approved these changes

2023-06-28 14:05 UTC, merged