video player
hlxsites/troweprice-rf pull request #32
Opened 2023-06-28 13:41 UTC by sergiucoman

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #9
Fix #11 

Test URLs:
- After: https://feat-video--troweprice-rf--hlxsites.hlx.page/drafts/scoman/plan-learn

2023-06-28 14:36 UTC, bstopp commented on blocks/brightcove/brightcove.js
> +      <video-js autoplay data-video-id="${videoId}" data-account="1305038892" data-player="hrZH04vdb" data-embed="default" controls="" data-application-id="" class="vjs-fluid"></video-js>
Player and account data elements need to be dynamic. I think they have multiple player types on this site?

Account can be a global metadata value.
Player can be a config option passed in the block definition

2023-07-12 08:01 UTC, sergiucoman commented on blocks/brightcove/brightcove.js
> +      <video-js autoplay data-video-id="${videoId}" data-account="1305038892" data-player="hrZH04vdb" data-embed="default" controls="" data-application-id="" class="vjs-fluid"></video-js>
Adeded video player with playlist and metadat for configuration.

2023-07-12 21:18 UTC, bstopp requested changes

2023-07-12 21:18 UTC, bstopp commented on blocks/video-series/video-series.css
> +.video-series.block .video-player .video-js .vjs-dock-text {
I don't think you need to specify any CSS more qualified than the player. All of the expeirence for the player should come from the player's CSS that is loaded when the JS is added to the page.

Is this not the case?

2023-07-13 12:24 UTC, bstopp approved these changes

2023-07-13 12:35 UTC, merged