Fixed footer after changes in global styles.
hlxsites/troweprice-rf pull request #47
Opened 2023-07-12 10:28 UTC by sergiucoman

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #46

Test URLs:
- Before: https://main--troweprice-rf--hlxsites.hlx.page/
- After: https://bugfix-footer--troweprice-rf--hlxsites.hlx.page/

2023-07-12 18:46 UTC, bstopp requested changes

2023-07-13 08:15 UTC, sergiucoman commented on styles/styles.css
> +  font-weight: var(--font-weight-normal);
Right, I had mistakenly changed the global CSS. The change should have been done only in footer.css. Reverted the change.

2023-07-13 08:53 UTC, dnbute commented on blocks/footer/footer.css
> +@media screen and (min-width: 960px) {
Was this left over from before we switched to the 600/900/1200 break points or is there a specific reason for the 960px?

2023-07-13 12:08 UTC, bstopp commented on blocks/footer/footer.css
> +@media screen and (min-width: 960px) {
Good Catch.

2023-07-13 12:39 UTC, sergiucoman commented on blocks/footer/footer.css
> +@media screen and (min-width: 960px) {
yeah, good catch. I was using the breakpoints from the original site. It is fixed now.

2023-07-13 13:32 UTC, dnbute approved these changes
lgtm

2023-07-13 15:36 UTC, bstopp approved these changes

2023-07-13 17:11 UTC, merged